// Define all needed elements from page or form.
const formElement = document.querySelector('#page-form')
const inputLastName = document.querySelector('#lname-input')
const inputFirstName = document.querySelector('#fname-input')
const inputEmail = document.querySelector('#email-input')
const serviceSelect = document.querySelector('#service-select')
const inputCountry = document.querySelector('#country-input')
const inputZip = document.querySelector('#zip-input')
const inputPass = document.querySelector('#pass-input')
const inputPassConf =document.querySelector('#pass-confirm')